-- =============================================================================
-- Home Snapshot Table
-- Stores daily materialised home page data.
-- One row per snapshot_date. Generated by first user login of the day.
-- Subsequent logins read from here — no Athena queries needed.
-- Database: zamboni_catalog
-- =============================================================================

CREATE TABLE IF NOT EXISTS zamboni_catalog.home_snapshot (

    snapshot_date           DATE        COMMENT 'Date this snapshot covers',
    generated_at            TIMESTAMP   COMMENT 'When this snapshot was generated',
    generated_by            STRING      COMMENT 'Username who triggered generation',

    -- KPI cards (JSON)
    kpi_json                STRING      COMMENT 'JSON: {total_tables, hk_enabled, failures_7d, gb_reclaimed_30d}',

    -- Fleet coverage (JSON array)
    fleet_coverage_json     STRING      COMMENT 'JSON array: [{domain, layer, total, enabled, pct}]',

    -- Top tables needing compaction (JSON array)
    compaction_needed_json  STRING      COMMENT 'JSON array: top 20 tables needing compaction',

    -- Recent failures (JSON array)
    recent_failures_json    STRING      COMMENT 'JSON array: failures in last 7 days',

    -- Domain summary (JSON array)
    domain_summary_json     STRING      COMMENT 'JSON array: per-domain table counts and status',

    -- Bytes reclaimed trend (JSON array)
    cost_trend_json         STRING      COMMENT 'JSON array: daily bytes reclaimed last 30 days'

)
LOCATION 's3://your-zamboni-metadata-bucket/home_snapshot/'
TBLPROPERTIES (
    'table_type'        = 'ICEBERG',
    'format'            = 'PARQUET',
    'write_compression' = 'SNAPPY'
);
